import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar"
import { DashboardFooter } from "@/components/Foooter/footer";
import { DashboardSidebar } from "@/components/sidebarelem/dashboardsidebar";
import { DashboardHeader } from "@/components/Headerdashboard/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning
      > 
       <SidebarProvider>
      <div className="flex min-h-screen bg-background w-screen m-2">
        <DashboardSidebar />
        <SidebarInset>
          <div className="flex flex-col w-full">
            <DashboardHeader />
            <main className="flex-1 w-full">{children}</main>
            <DashboardFooter />
          </div>
        </SidebarInset>
      </div>
    </SidebarProvider>
      </body>
    </html>
  );
}
